### ISSUE TITLE
[Bug] IdToAddressBiMap should not accept uint16(-1) nor address(0)

### ISSUE THREAD

**Issue by fleupold** [gnosis/solidity-data-structures#10]
Inserting one of the two values may lead to weird behavior.

In particular

```solidity
map.insert(42, address(0));
map.hadId(42) -> false
map.hadAddress(address(0)) -> true

map.insert(uint16(-1), address(42));
map.hadId(uint16(-1)) -> true
map.hadAddress(address(42)) -> false
```

We should probably just forbid adding either of the two values.

**Comment by josojo** [comment]
Is this issue still persistent?

It looks like it is fixed...
https://github.com/gnosis/solidity-data-structures/blob/master/contracts/libraries/IdToAddressBiMap.sol#L29

But I want confirmation before closing this issue...

**Comment by fleupold** [comment]
Yes, it is fixed via https://github.com/gnosis/solidity-data-structures/pull/12
